---
- hosts: localhost

  vars:
    source_key: "./.ssh/id_rsa"
    dest_key: "{{ lookup('env', 'HOME') }}/.ssh/id_rsa"
    personal: "{{ lookup('env', 'HOME') }}/personal"

  pre_tasks:
    - name: update cache
      apt:
        update_cache: true
        force_apt_get: true
        state: present
      become: true
      tags:
        - install
        - core

  tasks:
    - include: tasks/ssh.yml
    - include: tasks/core.yml
    - include: tasks/git.yml
    - include: tasks/zsh.yml
    - include: tasks/cargo.yml
    - include: tasks/node.yml
    - include: tasks/npm-packages.yml
    - include: tasks/nvim.yml
    - include: tasks/dotfiles.yml
    - include: tasks/productivity-tools.yml
    - include: tasks/install-alacritty.yml
    - include: tasks/terraform.yml
