- name: Add Hashicorp GPG key
  shell: wget -O- https://apt.releases.hashicorp.com/gpg | sudo gpg --dearmor | sudo tee /usr/share/keyrings/hashicorp-archive-keyring.gpg
  become: true
  tags:
    - terraform

- name: Add Hashicorp repo to system
  shell: echo "deb [signed-by=/usr/share/keyrings/hashicorp-archive-keyring.gpg] https://apt.releases.hashicorp.com $(lsb_release -cs) main" | sudo tee /etc/apt/sources.list.d/hashicorp.list
  become: true
  tags:
    - terraform

- name: Install Terraform
  apt:
    name: terraform
    update_cache: true
  become: true
  tags:
    - terraform
